# Generated by Django 3.2.18 on 2023-05-02 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_type', models.CharField(max_length=30, verbose_name='Тип оборудования')),
                ('mask_sn', models.TextField(verbose_name='Маска SN')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField()),
                ('equipment_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mask_app.equipment_type')),
            ],
        ),
    ]
